# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: MIT-0

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
